name: KEYWORD RELEASE TEST 

on: 
  push:
    branches: 
      - develop
# trigger commits 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gtamang001/keyword-release-action@develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keyword: 'FIXED'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# add commet line 
# trigger commet 