name: KEYWORD RELEASE TEST 

on: 
  push:
    branches: 
      - develop 
# trigger commits 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gtamang001/keyword-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'FIXED'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# add commet line 