name: Release workflow 
on: 
  workflow_dispatch: 
env: 
  VERSION: 0.2.0
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{env.VERSION}}
          release_name: Release ${{env.VERSION}}
          body: |
            ## Changes in this Release
            - First Change
            - Second Change
            ### Second changes 
          draft: false
          prerelease: false