name: Release workflow 
on:
  workflow_dispatch: 

env: 
  VERSION: 0.3.0
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: get current version 
        run: |
          # VERSION=$(git describe --tags | cut -d '-' -f 1)
          touch version.txt 
          echo "0.4.0" >> $VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{env.VERSION}}
          release_name: Release ${{env.VERSION}}
          body_path: ${{github.workspace}}/changelog.md
          draft: false
          prerelease: false
  check-release: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code 
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: check the last tag 
        run: |
          version=$(git describe --tags)
          echo $version

