name: Release workflow 
on:
  push: 
    branches: 
      - develop
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: get current version 
        run: |
          VERSION="0.4.0"
          touch version.txt
          echo $VERSION >> version.txt 
          export RVERSION=$(cat version.txt)

      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $RVERSION
          release_name: Release $RVERSION
          body_path: ${{github.workspace}}/changelog.md
          draft: false
          prerelease: false
  check-release: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code 
        uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: check the last tag 
        run: |
          version=$(git describe --tags)
          echo $version

