name: keyword-releaser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gtamang001/keyword-release-action@master
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        args: 'FIXED'
